<?php

return [
    'name' => '001_initial_schema',
    'sqlite' => [
        'CREATE TABLE IF NOT EXISTS shows (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            show_name TEXT NOT NULL,
            theatre_name TEXT NOT NULL,
            shop_name TEXT NOT NULL,
            ld_name TEXT NOT NULL,
            ld_email TEXT NOT NULL,
            ld_phone TEXT NOT NULL,
            assistant_ld_name TEXT NOT NULL,
            assistant_ld_email TEXT NOT NULL,
            assistant_ld_phone TEXT NOT NULL,
            production_electrician_name TEXT NOT NULL,
            production_electrician_email TEXT NOT NULL,
            production_electrician_phone TEXT NOT NULL,
            shop_manager_name TEXT NOT NULL,
            shop_manager_email TEXT NOT NULL,
            shop_manager_phone TEXT NOT NULL,
            assistant_shop_manager_name TEXT NOT NULL,
            assistant_shop_manager_email TEXT NOT NULL,
            assistant_shop_manager_phone TEXT NOT NULL,
            show_image_url TEXT DEFAULT NULL,
            pull_date TEXT DEFAULT NULL,
            return_date TEXT DEFAULT NULL,
            strike_date TEXT DEFAULT NULL,
            opening_date TEXT DEFAULT NULL,
            closing_date TEXT DEFAULT NULL,
            theatre_address TEXT DEFAULT NULL,
            shop_address TEXT DEFAULT NULL,
            show_notes TEXT DEFAULT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )',
        'CREATE TABLE IF NOT EXISTS inventory_categories (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL UNIQUE,
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )',
        'CREATE TABLE IF NOT EXISTS inventory_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            category_id INTEGER DEFAULT NULL,
            name TEXT NOT NULL,
            shop_quantity INTEGER NOT NULL DEFAULT 0,
            unit TEXT DEFAULT NULL,
            default_note TEXT DEFAULT NULL,
            description TEXT DEFAULT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (category_id) REFERENCES inventory_categories(id) ON DELETE SET NULL
        )',
        'CREATE UNIQUE INDEX IF NOT EXISTS inventory_items_unique_name ON inventory_items(category_id, name)',
        'CREATE TABLE IF NOT EXISTS show_revisions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            show_id INTEGER NOT NULL,
            revision_code TEXT NOT NULL,
            revision_index INTEGER NOT NULL,
            revision_date TEXT NOT NULL,
            is_initial INTEGER NOT NULL DEFAULT 0,
            summary_note TEXT DEFAULT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (show_id) REFERENCES shows(id) ON DELETE CASCADE,
            UNIQUE (show_id, revision_code)
        )',
        'CREATE TABLE IF NOT EXISTS revision_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            revision_id INTEGER NOT NULL,
            inventory_item_id INTEGER NOT NULL,
            rent_quantity INTEGER NOT NULL DEFAULT 0,
            spare_quantity INTEGER NOT NULL DEFAULT 0,
            total_quantity INTEGER NOT NULL DEFAULT 0,
            action TEXT NOT NULL DEFAULT \'\',
            line_note TEXT DEFAULT NULL,
            pickup_date TEXT DEFAULT NULL,
            return_date TEXT DEFAULT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (revision_id) REFERENCES show_revisions(id) ON DELETE CASCADE,
            FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
            UNIQUE (revision_id, inventory_item_id)
        )',
        'CREATE TABLE IF NOT EXISTS system_rules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            trigger_item_id INTEGER NOT NULL,
            trigger_quantity INTEGER NOT NULL DEFAULT 1,
            required_item_id INTEGER NOT NULL,
            required_quantity INTEGER NOT NULL DEFAULT 1,
            note TEXT DEFAULT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (trigger_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
            FOREIGN KEY (required_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE
        )',
        'CREATE TABLE IF NOT EXISTS app_settings (
            `key` TEXT PRIMARY KEY,
            value TEXT DEFAULT NULL,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )',
        'INSERT OR IGNORE INTO inventory_categories (id, name, sort_order) VALUES
            (1, \'Fixtures\', 1),
            (2, \'Power\', 2),
            (3, \'Control\', 3),
            (4, \'Accessories\', 4)',
        'INSERT OR IGNORE INTO inventory_items (id, category_id, name, shop_quantity, unit, default_note, description) VALUES
            (1, 1, \'SolaFrame 3000\', 12, \'ea\', \'Profile moving light\', \'Starter fixture inventory row\'),
            (2, 2, \'Stagepin to True1 Adapter\', 20, \'ea\', \'Often paired with SolaFrames\', \'Adapter example for global rules\'),
            (3, 3, \'Tech Table Package\', 2, \'pkg\', \'Use custom pull dates when needed\', \'Control package example\'),
            (4, 4, \'Workbox\', 6, \'ea\', \'Contains hand tools and consumables\', \'Accessory with default note example\'),
            (5, 4, \'Genie Lift\', 1, \'ea\', \'Set a specific item pull/return date when needed\', \'Lift scheduling example\')',
        'INSERT OR IGNORE INTO system_rules (id, trigger_item_id, trigger_quantity, required_item_id, required_quantity, note) VALUES
            (1, 1, 1, 2, 1, \'Each SolaFrame typically needs one stagepin to True1 adapter.\')',
        'INSERT OR IGNORE INTO app_settings (`key`, value) VALUES
            (\'layout.header_text\', \'Production Electrician Shop Order\'),
            (\'layout.footer_text\', \'Prepared in PE Work\'),
            (\'layout.show_image\', \'1\'),
            (\'layout.show_page_numbers\', \'1\'),
            (\'layout.show_revision_summary\', \'1\')',
    ],
    'mysql' => [
        'CREATE TABLE IF NOT EXISTS shows (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            show_name VARCHAR(255) NOT NULL,
            theatre_name VARCHAR(255) NOT NULL,
            shop_name VARCHAR(255) NOT NULL,
            ld_name VARCHAR(255) NOT NULL,
            ld_email VARCHAR(255) NOT NULL,
            ld_phone VARCHAR(50) NOT NULL,
            assistant_ld_name VARCHAR(255) NOT NULL,
            assistant_ld_email VARCHAR(255) NOT NULL,
            assistant_ld_phone VARCHAR(50) NOT NULL,
            production_electrician_name VARCHAR(255) NOT NULL,
            production_electrician_email VARCHAR(255) NOT NULL,
            production_electrician_phone VARCHAR(50) NOT NULL,
            shop_manager_name VARCHAR(255) NOT NULL,
            shop_manager_email VARCHAR(255) NOT NULL,
            shop_manager_phone VARCHAR(50) NOT NULL,
            assistant_shop_manager_name VARCHAR(255) NOT NULL,
            assistant_shop_manager_email VARCHAR(255) NOT NULL,
            assistant_shop_manager_phone VARCHAR(50) NOT NULL,
            show_image_url TEXT DEFAULT NULL,
            pull_date DATE DEFAULT NULL,
            return_date DATE DEFAULT NULL,
            strike_date DATE DEFAULT NULL,
            opening_date DATE DEFAULT NULL,
            closing_date DATE DEFAULT NULL,
            theatre_address TEXT DEFAULT NULL,
            shop_address TEXT DEFAULT NULL,
            show_notes TEXT DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS inventory_categories (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255) NOT NULL UNIQUE,
            sort_order INT NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS inventory_items (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            category_id INT UNSIGNED DEFAULT NULL,
            name VARCHAR(255) NOT NULL,
            shop_quantity INT NOT NULL DEFAULT 0,
            unit VARCHAR(50) DEFAULT NULL,
            default_note TEXT DEFAULT NULL,
            description TEXT DEFAULT NULL,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY inventory_items_unique_name (category_id, name),
            CONSTRAINT fk_inventory_items_category FOREIGN KEY (category_id) REFERENCES inventory_categories(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS show_revisions (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            show_id INT UNSIGNED NOT NULL,
            revision_code VARCHAR(120) NOT NULL,
            revision_index INT NOT NULL,
            revision_date DATE NOT NULL,
            is_initial TINYINT(1) NOT NULL DEFAULT 0,
            summary_note TEXT DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY show_revision_code_unique (show_id, revision_code),
            CONSTRAINT fk_show_revisions_show FOREIGN KEY (show_id) REFERENCES shows(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS revision_items (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            revision_id INT UNSIGNED NOT NULL,
            inventory_item_id INT UNSIGNED NOT NULL,
            rent_quantity INT NOT NULL DEFAULT 0,
            spare_quantity INT NOT NULL DEFAULT 0,
            total_quantity INT NOT NULL DEFAULT 0,
            action VARCHAR(20) NOT NULL DEFAULT \'\',
            line_note TEXT DEFAULT NULL,
            pickup_date DATE DEFAULT NULL,
            return_date DATE DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY revision_item_unique (revision_id, inventory_item_id),
            CONSTRAINT fk_revision_items_revision FOREIGN KEY (revision_id) REFERENCES show_revisions(id) ON DELETE CASCADE,
            CONSTRAINT fk_revision_items_inventory FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS system_rules (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            trigger_item_id INT UNSIGNED NOT NULL,
            trigger_quantity INT NOT NULL DEFAULT 1,
            required_item_id INT UNSIGNED NOT NULL,
            required_quantity INT NOT NULL DEFAULT 1,
            note TEXT DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_system_rules_trigger FOREIGN KEY (trigger_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
            CONSTRAINT fk_system_rules_required FOREIGN KEY (required_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS app_settings (
            `key` VARCHAR(120) PRIMARY KEY,
            value TEXT DEFAULT NULL,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'INSERT IGNORE INTO inventory_categories (id, name, sort_order) VALUES
            (1, \'Fixtures\', 1),
            (2, \'Power\', 2),
            (3, \'Control\', 3),
            (4, \'Accessories\', 4)',
        'INSERT IGNORE INTO inventory_items (id, category_id, name, shop_quantity, unit, default_note, description) VALUES
            (1, 1, \'SolaFrame 3000\', 12, \'ea\', \'Profile moving light\', \'Starter fixture inventory row\'),
            (2, 2, \'Stagepin to True1 Adapter\', 20, \'ea\', \'Often paired with SolaFrames\', \'Adapter example for global rules\'),
            (3, 3, \'Tech Table Package\', 2, \'pkg\', \'Use custom pull dates when needed\', \'Control package example\'),
            (4, 4, \'Workbox\', 6, \'ea\', \'Contains hand tools and consumables\', \'Accessory with default note example\'),
            (5, 4, \'Genie Lift\', 1, \'ea\', \'Set a specific item pull/return date when needed\', \'Lift scheduling example\')',
        'INSERT IGNORE INTO system_rules (id, trigger_item_id, trigger_quantity, required_item_id, required_quantity, note) VALUES
            (1, 1, 1, 2, 1, \'Each SolaFrame typically needs one stagepin to True1 adapter.\')',
        'INSERT IGNORE INTO app_settings (`key`, value) VALUES
            (\'layout.header_text\', \'Production Electrician Shop Order\'),
            (\'layout.footer_text\', \'Prepared in PE Work\'),
            (\'layout.show_image\', \'1\'),
            (\'layout.show_page_numbers\', \'1\'),
            (\'layout.show_revision_summary\', \'1\')',
    ],
];
