<?php

/**
 * Standalone paperwork export settings snapshot for PE-Work / Backline.
 *
 * Copy this file into another PHP project and load it with:
 *   $paperwork = require __DIR__ . '/paperwork_export_settings_reference.php';
 *
 * The `configurable_options` block is intentionally first so another AI agent
 * can immediately see every current paperwork export field, its setting key,
 * input name, section, type, whether it can be overridden per show, and what
 * the current value/default is.
 */

return [
    'configurable_options' => [
        [
            'section' => 'general',
            'label' => 'Header Text',
            'input_name' => 'header_text',
            'setting_key' => 'layout.header_text',
            'type' => 'text',
            'show_override' => true,
            'current_value' => 'Production Electrician Shop Order',
            'default_value' => 'Production Electrician Shop Order',
        ],
        [
            'section' => 'general',
            'label' => 'Top Right Header Text',
            'input_name' => 'organization_text',
            'setting_key' => 'layout.organization_text',
            'type' => 'text',
            'show_override' => true,
            'current_value' => '',
            'default_value' => '',
        ],
        [
            'section' => 'general',
            'label' => 'Footer Text',
            'input_name' => 'footer_text',
            'setting_key' => 'layout.footer_text',
            'type' => 'text',
            'show_override' => true,
            'current_value' => 'Prepared in Backline',
            'default_value' => 'Prepared in Backline',
        ],
        [
            'section' => 'general',
            'label' => 'Default Important Notes',
            'input_name' => 'export_notes',
            'setting_key' => 'layout.export_notes',
            'type' => 'textarea',
            'show_override' => true,
            'current_value' => "Unless otherwise noted, all units to come with lamp, c-clamp, safety cable and black color frame.\nAll hardware, perishables, cable lengths and power distribution requirements as per electrician.\nAbsolutely no substitutions without written permission of Designer.\nAny revisions or substitutions must be fully disclosed.\nShop assumes responsibility for any additional materials that are required on site due to rental shop oversight or error.\nAll PAR cans to have interior protective screening.\nColor scrolls to be made and loaded by shop. A list of required colors will be provided.",
            'default_value' => "Unless otherwise noted, all units to come with lamp, c-clamp, safety cable and black color frame.\nAll hardware, perishables, cable lengths and power distribution requirements as per electrician.\nAbsolutely no substitutions without written permission of Designer.\nAny revisions or substitutions must be fully disclosed.\nShop assumes responsibility for any additional materials that are required on site due to rental shop oversight or error.\nAll PAR cans to have interior protective screening.\nColor scrolls to be made and loaded by shop. A list of required colors will be provided.",
        ],
        [
            'section' => 'general',
            'label' => 'Show image on exports',
            'input_name' => 'show_image',
            'setting_key' => 'layout.show_image',
            'type' => 'checkbox',
            'show_override' => true,
            'current_value' => '1',
            'default_value' => '1',
        ],
        [
            'section' => 'general',
            'label' => 'Show title above cover image',
            'input_name' => 'cover_show_title',
            'setting_key' => 'layout.cover_show_title',
            'type' => 'checkbox',
            'show_override' => true,
            'current_value' => '1',
            'default_value' => '1',
        ],
        [
            'section' => 'general',
            'label' => 'Page X of X',
            'input_name' => 'show_page_numbers',
            'setting_key' => 'layout.show_page_numbers',
            'type' => 'checkbox',
            'show_override' => true,
            'current_value' => '1',
            'default_value' => '1',
        ],
        [
            'section' => 'general',
            'label' => 'Revision summary block',
            'input_name' => 'show_revision_summary',
            'setting_key' => 'layout.show_revision_summary',
            'type' => 'checkbox',
            'show_override' => true,
            'current_value' => '1',
            'default_value' => '1',
        ],
        [
            'section' => 'cover',
            'label' => 'Cover Title To Revision Spacing (in)',
            'input_name' => 'cover_title_revision_spacing',
            'setting_key' => 'layout.cover_title_revision_spacing',
            'type' => 'decimal',
            'show_override' => true,
            'current_value' => '0.52',
            'default_value' => '0.52',
        ],
        [
            'section' => 'cover',
            'label' => 'Cards To Notes Spacing (in)',
            'input_name' => 'cover_notes_spacing',
            'setting_key' => 'layout.cover_notes_spacing',
            'type' => 'decimal',
            'show_override' => true,
            'current_value' => '0.9',
            'default_value' => '0.9',
        ],
        [
            'section' => 'cover',
            'label' => 'Cover Footer Logo Path',
            'input_name' => 'cover_footer_logo_url',
            'setting_key' => 'layout.cover_footer_logo_url',
            'type' => 'local_asset_path',
            'show_override' => true,
            'current_value' => '',
            'default_value' => '',
        ],
        [
            'section' => 'cover',
            'label' => 'Prepared By Name',
            'input_name' => 'cover_prepared_by_name',
            'setting_key' => 'layout.cover_prepared_by_name',
            'type' => 'text',
            'show_override' => true,
            'current_value' => '',
            'default_value' => '',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Table Width %',
            'input_name' => 'revision_summary_table_width',
            'setting_key' => 'layout.revision_summary_table_width',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '100',
            'default_value' => '100',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Min Rows Per Page',
            'input_name' => 'revision_summary_min_rows_per_page',
            'setting_key' => 'layout.revision_summary_min_rows_per_page',
            'type' => 'integer',
            'show_override' => false,
            'current_value' => '0',
            'default_value' => '0',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Max Rows Per Page',
            'input_name' => 'revision_summary_max_rows_per_page',
            'setting_key' => 'layout.revision_summary_max_rows_per_page',
            'type' => 'integer',
            'show_override' => false,
            'current_value' => '0',
            'default_value' => '0',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Line Number Width',
            'input_name' => 'revision_summary_col_line',
            'setting_key' => 'layout.revision_summary_col_line',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '4',
            'default_value' => '4',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Item Width',
            'input_name' => 'revision_summary_col_item',
            'setting_key' => 'layout.revision_summary_col_item',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '45',
            'default_value' => '45',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Description Width',
            'input_name' => 'revision_summary_col_description',
            'setting_key' => 'layout.revision_summary_col_description',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '23',
            'default_value' => '23',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Previous Total Width',
            'input_name' => 'revision_summary_col_previous_total',
            'setting_key' => 'layout.revision_summary_col_previous_total',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '6',
            'default_value' => '6',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Total Width',
            'input_name' => 'revision_summary_col_total',
            'setting_key' => 'layout.revision_summary_col_total',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '6',
            'default_value' => '6',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Action Width',
            'input_name' => 'revision_summary_col_action',
            'setting_key' => 'layout.revision_summary_col_action',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '10',
            'default_value' => '10',
        ],
        [
            'section' => 'revision_summary',
            'label' => 'Notes Width',
            'input_name' => 'revision_summary_col_notes',
            'setting_key' => 'layout.revision_summary_col_notes',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '12',
            'default_value' => '12',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Table Width %',
            'input_name' => 'equipment_table_width',
            'setting_key' => 'layout.equipment_table_width',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '100',
            'default_value' => '100',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Min Rows Per Page',
            'input_name' => 'equipment_min_rows_per_page',
            'setting_key' => 'layout.equipment_min_rows_per_page',
            'type' => 'integer',
            'show_override' => false,
            'current_value' => '0',
            'default_value' => '0',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Max Rows Per Page',
            'input_name' => 'equipment_max_rows_per_page',
            'setting_key' => 'layout.equipment_max_rows_per_page',
            'type' => 'integer',
            'show_override' => false,
            'current_value' => '0',
            'default_value' => '0',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Gray Row Color',
            'input_name' => 'equipment_zebra_gray',
            'setting_key' => 'layout.equipment_zebra_gray',
            'type' => 'color',
            'show_override' => false,
            'current_value' => '#CCCCCC',
            'default_value' => '#CCCCCC',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Line Item Row Padding (in)',
            'input_name' => 'equipment_row_padding',
            'setting_key' => 'layout.equipment_row_padding',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '0.016',
            'default_value' => '0.016',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Header Row Height (in)',
            'input_name' => 'equipment_header_row_padding',
            'setting_key' => 'layout.equipment_header_row_padding',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '0.22',
            'default_value' => '0.22',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Category Row Height (in)',
            'input_name' => 'equipment_category_row_padding',
            'setting_key' => 'layout.equipment_category_row_padding',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '0.26',
            'default_value' => '0.26',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Space Above Categories (in)',
            'input_name' => 'equipment_category_gap',
            'setting_key' => 'layout.equipment_category_gap',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '0.08',
            'default_value' => '0.08',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Font Size (pt)',
            'input_name' => 'equipment_font_size',
            'setting_key' => 'layout.equipment_font_size',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '7.35',
            'default_value' => '7.35',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Header Row Color',
            'input_name' => 'equipment_header_fill',
            'setting_key' => 'layout.equipment_header_fill',
            'type' => 'color',
            'show_override' => false,
            'current_value' => '#F3F4F6',
            'default_value' => '#F3F4F6',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Category Row Color',
            'input_name' => 'equipment_category_fill',
            'setting_key' => 'layout.equipment_category_fill',
            'type' => 'color',
            'show_override' => false,
            'current_value' => '#E5E7EB',
            'default_value' => '#E5E7EB',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Line Height',
            'input_name' => 'equipment_line_height',
            'setting_key' => 'layout.equipment_line_height',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '1.1',
            'default_value' => '1.1',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Line Number Width',
            'input_name' => 'equipment_col_line',
            'setting_key' => 'layout.equipment_col_line',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '4',
            'default_value' => '4',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Item Width',
            'input_name' => 'equipment_col_item',
            'setting_key' => 'layout.equipment_col_item',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '45',
            'default_value' => '45',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Description Width',
            'input_name' => 'equipment_col_description',
            'setting_key' => 'layout.equipment_col_description',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '23',
            'default_value' => '23',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Used Width',
            'input_name' => 'equipment_col_used',
            'setting_key' => 'layout.equipment_col_used',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '5',
            'default_value' => '5',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Spare Width',
            'input_name' => 'equipment_col_spare',
            'setting_key' => 'layout.equipment_col_spare',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '5',
            'default_value' => '5',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Total Width',
            'input_name' => 'equipment_col_total',
            'setting_key' => 'layout.equipment_col_total',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '6',
            'default_value' => '6',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Notes Width',
            'input_name' => 'equipment_col_notes',
            'setting_key' => 'layout.equipment_col_notes',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '12',
            'default_value' => '12',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Line Number Font Size (pt)',
            'input_name' => 'equipment_font_line',
            'setting_key' => 'layout.equipment_font_line',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '6.9',
            'default_value' => '6.9',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Item Font Size (pt)',
            'input_name' => 'equipment_font_item',
            'setting_key' => 'layout.equipment_font_item',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '7.35',
            'default_value' => '7.35',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Description Font Size (pt)',
            'input_name' => 'equipment_font_description',
            'setting_key' => 'layout.equipment_font_description',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '7.35',
            'default_value' => '7.35',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Used Font Size (pt)',
            'input_name' => 'equipment_font_used',
            'setting_key' => 'layout.equipment_font_used',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '7.35',
            'default_value' => '7.35',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Spare Font Size (pt)',
            'input_name' => 'equipment_font_spare',
            'setting_key' => 'layout.equipment_font_spare',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '7.35',
            'default_value' => '7.35',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Total Font Size (pt)',
            'input_name' => 'equipment_font_total',
            'setting_key' => 'layout.equipment_font_total',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '7.35',
            'default_value' => '7.35',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Action Font Size (pt)',
            'input_name' => 'equipment_font_action',
            'setting_key' => 'layout.equipment_font_action',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '7.35',
            'default_value' => '7.35',
        ],
        [
            'section' => 'equipment_breakdown',
            'label' => 'Notes Font Size (pt)',
            'input_name' => 'equipment_font_notes',
            'setting_key' => 'layout.equipment_font_notes',
            'type' => 'decimal',
            'show_override' => false,
            'current_value' => '7.35',
            'default_value' => '7.35',
        ],
    ],

    'companion_template_file' => 'paperwork_export_template_reference.php',

    'paperwork_sections' => [
        'general' => 'Global paperwork text and export toggles.',
        'cover' => 'Cover-page spacing and footer identity fields.',
        'revision_summary' => 'Revision summary table widths and pagination controls.',
        'equipment_breakdown' => 'Equipment table colors, spacing, column widths, and font sizes.',
    ],

    'current_export_settings' => [
        'layout.header_text' => 'Production Electrician Shop Order',
        'layout.organization_text' => '',
        'layout.footer_text' => 'Prepared in Backline',
        'layout.export_notes' => "Unless otherwise noted, all units to come with lamp, c-clamp, safety cable and black color frame.\nAll hardware, perishables, cable lengths and power distribution requirements as per electrician.\nAbsolutely no substitutions without written permission of Designer.\nAny revisions or substitutions must be fully disclosed.\nShop assumes responsibility for any additional materials that are required on site due to rental shop oversight or error.\nAll PAR cans to have interior protective screening.\nColor scrolls to be made and loaded by shop. A list of required colors will be provided.",
        'layout.show_image' => '1',
        'layout.cover_show_title' => '1',
        'layout.show_page_numbers' => '1',
        'layout.show_revision_summary' => '1',
        'layout.cover_title_revision_spacing' => '0.52',
        'layout.cover_notes_spacing' => '0.9',
        'layout.cover_footer_logo_url' => '',
        'layout.cover_prepared_by_name' => '',
        'layout.equipment_table_width' => '100',
        'layout.equipment_min_rows_per_page' => '0',
        'layout.equipment_max_rows_per_page' => '0',
        'layout.revision_summary_table_width' => '100',
        'layout.revision_summary_min_rows_per_page' => '0',
        'layout.revision_summary_max_rows_per_page' => '0',
        'layout.revision_summary_col_line' => '4',
        'layout.revision_summary_col_item' => '45',
        'layout.revision_summary_col_description' => '23',
        'layout.revision_summary_col_previous_total' => '6',
        'layout.revision_summary_col_total' => '6',
        'layout.revision_summary_col_action' => '10',
        'layout.revision_summary_col_notes' => '12',
        'layout.equipment_zebra_gray' => '#CCCCCC',
        'layout.equipment_row_padding' => '0.016',
        'layout.equipment_header_row_padding' => '0.22',
        'layout.equipment_category_row_padding' => '0.26',
        'layout.equipment_category_gap' => '0.08',
        'layout.equipment_header_fill' => '#F3F4F6',
        'layout.equipment_category_fill' => '#E5E7EB',
        'layout.equipment_font_size' => '7.35',
        'layout.equipment_line_height' => '1.1',
        'layout.equipment_col_line' => '4',
        'layout.equipment_col_item' => '45',
        'layout.equipment_col_description' => '23',
        'layout.equipment_col_used' => '5',
        'layout.equipment_col_spare' => '5',
        'layout.equipment_col_total' => '6',
        'layout.equipment_col_notes' => '12',
        'layout.equipment_font_line' => '6.9',
        'layout.equipment_font_item' => '7.35',
        'layout.equipment_font_description' => '7.35',
        'layout.equipment_font_used' => '7.35',
        'layout.equipment_font_spare' => '7.35',
        'layout.equipment_font_total' => '7.35',
        'layout.equipment_font_action' => '7.35',
        'layout.equipment_font_notes' => '7.35',
    ],

    'builtin_defaults' => [
        'layout.header_text' => 'Production Electrician Shop Order',
        'layout.organization_text' => '',
        'layout.footer_text' => 'Prepared in Backline',
        'layout.export_notes' => "Unless otherwise noted, all units to come with lamp, c-clamp, safety cable and black color frame.\nAll hardware, perishables, cable lengths and power distribution requirements as per electrician.\nAbsolutely no substitutions without written permission of Designer.\nAny revisions or substitutions must be fully disclosed.\nShop assumes responsibility for any additional materials that are required on site due to rental shop oversight or error.\nAll PAR cans to have interior protective screening.\nColor scrolls to be made and loaded by shop. A list of required colors will be provided.",
        'layout.show_image' => '1',
        'layout.cover_show_title' => '1',
        'layout.show_page_numbers' => '1',
        'layout.show_revision_summary' => '1',
        'layout.cover_title_revision_spacing' => '0.52',
        'layout.cover_notes_spacing' => '0.9',
        'layout.cover_footer_logo_url' => '',
        'layout.cover_prepared_by_name' => '',
        'layout.equipment_table_width' => '100',
        'layout.equipment_min_rows_per_page' => '0',
        'layout.equipment_max_rows_per_page' => '0',
        'layout.revision_summary_table_width' => '100',
        'layout.revision_summary_min_rows_per_page' => '0',
        'layout.revision_summary_max_rows_per_page' => '0',
        'layout.revision_summary_col_line' => '4',
        'layout.revision_summary_col_item' => '45',
        'layout.revision_summary_col_description' => '23',
        'layout.revision_summary_col_previous_total' => '6',
        'layout.revision_summary_col_total' => '6',
        'layout.revision_summary_col_action' => '10',
        'layout.revision_summary_col_notes' => '12',
        'layout.equipment_zebra_gray' => '#CCCCCC',
        'layout.equipment_row_padding' => '0.016',
        'layout.equipment_header_row_padding' => '0.22',
        'layout.equipment_category_row_padding' => '0.26',
        'layout.equipment_category_gap' => '0.08',
        'layout.equipment_header_fill' => '#F3F4F6',
        'layout.equipment_category_fill' => '#E5E7EB',
        'layout.equipment_font_size' => '7.35',
        'layout.equipment_line_height' => '1.1',
        'layout.equipment_col_line' => '4',
        'layout.equipment_col_item' => '45',
        'layout.equipment_col_description' => '23',
        'layout.equipment_col_used' => '5',
        'layout.equipment_col_spare' => '5',
        'layout.equipment_col_total' => '6',
        'layout.equipment_col_notes' => '12',
        'layout.equipment_font_line' => '6.9',
        'layout.equipment_font_item' => '7.35',
        'layout.equipment_font_description' => '7.35',
        'layout.equipment_font_used' => '7.35',
        'layout.equipment_font_spare' => '7.35',
        'layout.equipment_font_total' => '7.35',
        'layout.equipment_font_action' => '7.35',
        'layout.equipment_font_notes' => '7.35',
    ],

    'show_override_keys' => [
        'layout.header_text',
        'layout.organization_text',
        'layout.footer_text',
        'layout.export_notes',
        'layout.show_image',
        'layout.cover_show_title',
        'layout.show_page_numbers',
        'layout.show_revision_summary',
        'layout.cover_title_revision_spacing',
        'layout.cover_notes_spacing',
        'layout.cover_footer_logo_url',
        'layout.cover_prepared_by_name',
    ],

    'show_checkbox_inputs' => [
        'show_image',
        'cover_show_title',
        'show_page_numbers',
        'show_revision_summary',
    ],
];
